# Site settings
title: circle of friends | blog
email: me@pindarsign.de
description: ""
baseurl: "/circle-of-friends-blog"
url: "http://www.pindarsign.com"
twitter_username: SimonDittlmann
github_username:  SimonDittlmann

# Build settings
markdown: kramdown
permalink: pretty

# Gems
gems:
  - jekyll-redirect-from
