# Site settings
title: circle of friends | blog
email: me@pindarsign.de
description: ""
baseurl: ""
url: "http://www.pindarsign.com"
twitter_username: SimonDittlmann
github_username:  SimonDittlmann

# Build settings
markdown: kramdown
permalink: pretty

relative_permalinks: true

# Gems
gems:
  - jekyll-redirect-from

base_path : /circle-of-friends-blog/
